{
  "_from": "axios-error@^1.0.0-alpha.2",
  "_id": "axios-error@1.0.0-alpha.2",
  "_inBundle": false,
  "_integrity": "sha512-ElhuFlrVG0B3WBiMjrxlm8uidKF/7pq229aThtcps972Yebc5hv43SceWoLkh5NbWCGofALWJntRt8EiM+UARA==",
  "_location": "/axios-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "axios-error@^1.0.0-alpha.2",
    "name": "axios-error",
    "escapedName": "axios-error",
    "rawSpec": "^1.0.0-alpha.2",
    "saveSpec": null,
    "fetchSpec": "^1.0.0-alpha.2"
  },
  "_requiredBy": [
    "/messaging-api-line",
    "/messaging-api-messenger",
    "/messaging-api-slack",
    "/messaging-api-telegram",
    "/messaging-api-viber"
  ],
  "_resolved": "https://registry.npmjs.org/axios-error/-/axios-error-1.0.0-alpha.2.tgz",
  "_shasum": "076964c271b0d2071384dcd4a4c1c99ab01171b5",
  "_spec": "axios-error@^1.0.0-alpha.2",
  "_where": "/Users/billxu/chatBot/node_modules/messaging-api-line",
  "bugs": {
    "url": "https://github.com/Yoctol/messaging-apis/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "An axios error wrapper that aim to provide clear error message to the user",
  "devDependencies": {
    "axios": "^0.19.0",
    "axios-mock-adapter": "^1.17.0"
  },
  "engines": {
    "node": ">=8"
  },
  "gitHead": "7581219e17a1b1d9ab2f600e14f75b9714dd6fa0",
  "homepage": "https://github.com/Yoctol/messaging-apis#readme",
  "keywords": [
    "axios",
    "error",
    "http"
  ],
  "license": "MIT",
  "main": "dist/index.js",
  "name": "axios-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Yoctol/messaging-apis.git"
  },
  "types": "dist/index.d.ts",
  "version": "1.0.0-alpha.2"
}
